In [2]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import datetime 
from pandas import Timestamp


file_to_load = "parking.csv"


#Read Purchasing File and store into Pandas data frame
data_tickets = pd.read_csv(file_to_load)
data_tickets.head(2)

/Users/aracelymendoza/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (0,7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
0,1103341116,2015-12-21T00:00:00,1251.0,NaN,NaN,CA,200304.0,NaN,HOND,PA,GY,13147 WELBY WAY,01521,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0
1,1103700150,2015-12-21T00:00:00,1435.0,NaN,NaN,CA,201512.0,NaN,GMC,VN,WH,525 S MAIN ST,1C51,1.0,4000A1,NO EVIDENCE OF REG,50.0,99999.0,99999.0

In [3]:
# print(data_tickets['Issue Date'].isna().sum())

# (Basically convert the NA/NAn on ceros at the column Issue Data )
data_tickets['Issue Date'].fillna(0, inplace=True)

#convert str to dtype
data_tickets['Issue Date'] = data_tickets['Issue Date'].astype(str)

#Get all items star with 2018 at Issu Date 
data_tickets_2018 = data_tickets[data_tickets['Issue Date'].str.contains("2018")]


data_tickets_2018.sample(5)

,Ticket number,Issue Date,Issue time,Meter Id,Marked Time,RP State Plate,Plate Expiry Date,VIN,Make,Body Style,Color,Location,Route,Agency,Violation code,Violation Description,Fine amount,Latitude,Longitude
8372372,4342740824,2018-10-30T00:00:00,1117.0,NaN,NaN,CA,NaN,NaN,NISS,PA,GY,846 101ST,00500,55.0,80.69BS,NO PARK/STREET CLEAN,73.0,9.999900e+04,9.999900e+04
8471702,1125913401,2018-11-16T00:00:00,908.0,NaN,NaN,CA,201904.0,NaN,AUDI,PA,BK,2871 LOS FELIZ PLACE,00674,56.0,8069BS,NO PARK/STREET CLEAN,73.0,6.482217e+06,1.868452e+06
8571074,4344698993,2018-12-11T00:00:00,1503.0,NaN,1203.0,CA,201907.0,NaN,TOYT,VN,BL,422 MARIPOSA AVE S,00471,54.0,80.69C,PARKED OVER TIME LIMIT,58.0,6.471049e+06,1.846826e+06
7594782,4333629064,2018-06-01T00:00:00,949.0,NaN,NaN,CA,201901.0,NaN,NISS,PA,BK,3331 57TH ST W,00541,55.0,80.69BS,NO PARK/STREET CLEAN,73.0,6.461692e+06,1.819225e+06
7471158,4331890010,2018-05-10T00:00:00,1516.0,NaN,NaN,CA,201809.0,NaN,BMW,PA,SL,5400 SAN FERNANDO ROAD W,6T8,56.0,80.69A+,STOP/STAND PROHIBIT,93.0,6.478393e+06,1.877691e+06

In [4]:
# count unique values 
violation_count = data_tickets_2018["Violation code"].value_counts()

#Get the 10 tops 
violation_count.nlargest(10)

80.69BS     580848
88.13B+     292067
80.56E4+    155595
80.58L      143105
5204A-      123414
80.69B       88601
80.69C       62677
5200         58525
80.56E1      39972
80.69AP+     35850
Name: Violation code, dtype: int64

In [5]:
bins = [0, 59, 159, 259, 359, 459, 559, 659, 759, 859, 959, 1059, 1159, 1259, 1359, 1459, 1559, 1659, 1759, 1859, 1959, 2059, 2159, 2259, 2359]
group_names = ['12am-1am', '1am-2am', '2am-3am', '3am-4am', '4am-5am', '5am-6am', '6am-7am', '7am-8am', '8am-9am', '9am-10am', '10am-11am', '11am-12pm', '12pm-1pm', '1pm-2pm', '2pm-3pm', '3pm-4pm', '4pm-5pm', '5pm-6pm', '6pm-7pm', '7pm-8pm', '8pm-9pm', '9pm-10pm', '10pm,11pm', '11pm-12am']
data_tickets_2018["Time Day"] = pd.cut(data_tickets_2018["Issue time"], bins, labels=group_names)

hrs_group_demo = data_tickets_2018["Time Day"].value_counts()
tickets_x_hrs = data_tickets_2018.groupby("Time Day")
total_viola_cout = tickets_x_hrs ["Violation code"].value_counts()
# total_viola_cout


df = pd.DataFrame(hrs_group_demo)

/Users/aracelymendoza/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [6]:
data_tickets_2015.info()

NameError: name 'data_tickets_2015' is not defined